import { useState } from 'react';
import { Layout } from '@/components/layout/Layout';
import { Breadcrumbs } from '@/components/seo/Breadcrumbs';
import { ToolPageSEO } from '@/components/seo/ToolPageSEO';
import { ToolContentSection } from '@/components/seo/ToolContentSection';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { FileText, Copy } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

const seoData = {
  title: 'Robots.txt Generator Online Free - Create Robots.txt File',
  titleHi: 'Robots.txt जनरेटर ऑनलाइन फ्री',
  description: 'Free Robots.txt Generator - Create a proper robots.txt file for your website. Control search engine crawling and indexing easily.',
  descriptionHi: 'फ्री Robots.txt जनरेटर - अपनी website के लिए robots.txt file बनाएं।',
  keywords: ['robots.txt generator', 'create robots.txt', 'robots.txt maker', 'SEO robots file', 'search engine crawling'],
  canonicalUrl: '/tools/robots-generator',
  toolName: 'Robots.txt Generator',
  category: 'SEO Tool',
  faqs: [
    { question: 'Robots.txt क्या है?', answer: 'Robots.txt एक text file है जो search engine bots को बताती है कि website के कौन से pages crawl करने हैं और कौन से नहीं।' },
    { question: 'क्या robots.txt SEO के लिए ज़रूरी है?', answer: 'हाँ, proper robots.txt SEO के लिए important है। यह crawl budget optimize करता है और sensitive pages को index होने से रोकता है।' },
  ],
  howToSteps: ['Website URL enter करें', 'Allow/Disallow paths set करें', 'Sitemap URL add करें', 'Generate button click करें', 'File copy या download करें'],
};

const contentData = {
  whatIs: { title: 'Robots.txt Generator क्या है?', content: 'Robots.txt Generator एक free online SEO tool है जो आपकी website के लिए proper robots.txt file create करता है। Robots.txt file search engines (Google, Bing, etc.) को instructions देती है कि website के किन pages को crawl और index करना है। यह SEO optimization का important part है जो crawl budget manage करता है और admin/private pages को search results से बाहर रखता है।' },
  whyUse: { title: 'क्यों use करें?', points: ['Easy robots.txt creation', 'SEO optimization', 'Crawl budget management', 'Private pages protection', 'Sitemap integration'] },
  howToUse: { title: 'कैसे use करें', steps: ['Website domain enter करें', 'Disallow paths add करें', 'Sitemap URL enter करें', 'Generate button click करें', 'Copy करें और website root पर upload करें'] },
  useCases: { title: 'Use Cases', cases: ['New website setup', 'SEO audit fix', 'Admin pages hide', 'Crawl optimization', 'WordPress setup'] },
  faqs: seoData.faqs,
  relatedTools: [
    { title: 'Sitemap Generator', href: '/tools/sitemap-generator' },
    { title: 'Meta Tag Generator', href: '/tools/meta-generator' },
    { title: 'Keyword Density', href: '/tools/keyword-density' },
  ],
};

export default function RobotsGenerator() {
  const { toast } = useToast();
  const [domain, setDomain] = useState('');
  const [sitemapUrl, setSitemapUrl] = useState('');
  const [disallowPaths, setDisallowPaths] = useState('/admin/\n/wp-admin/\n/private/');
  const [allowAll, setAllowAll] = useState(true);
  const [result, setResult] = useState('');

  const generate = () => {
    let txt = '# Robots.txt generated by SmartToolsHub\n\n';
    txt += 'User-agent: *\n';
    if (allowAll) txt += 'Allow: /\n';
    disallowPaths.split('\n').filter(p => p.trim()).forEach(p => { txt += `Disallow: ${p.trim()}\n`; });
    txt += '\n';
    if (sitemapUrl.trim()) txt += `Sitemap: ${sitemapUrl.trim()}\n`;
    else if (domain.trim()) txt += `Sitemap: https://${domain.replace(/^https?:\/\//, '')}/sitemap.xml\n`;
    setResult(txt);
  };

  const copy = () => { navigator.clipboard.writeText(result); toast({ title: 'Copied!' }); };

  return (
    <Layout>
      <ToolPageSEO {...seoData} />
      <div className="container py-8 md:py-12">
        <div className="max-w-4xl mx-auto">
          <Breadcrumbs items={[{ label: 'Tools', href: '/tools' }, { label: 'Robots.txt Generator' }]} />
          <header className="text-center mb-8">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-sm mb-4"><FileText className="h-4 w-4" /><span>SEO Tool</span></div>
            <h1 className="font-display text-3xl md:text-4xl font-bold mb-2">Robots.txt Generator Online Free</h1>
            <p className="text-muted-foreground text-lg">अपनी website के लिए robots.txt file बनाएं</p>
          </header>

          <Card className="p-6 mb-6 space-y-4">
            <div className="grid sm:grid-cols-2 gap-4">
              <div><Label>Domain</Label><Input value={domain} onChange={e => setDomain(e.target.value)} placeholder="example.com" /></div>
              <div><Label>Sitemap URL (optional)</Label><Input value={sitemapUrl} onChange={e => setSitemapUrl(e.target.value)} placeholder="https://example.com/sitemap.xml" /></div>
            </div>
            <div><Label>Disallow Paths (one per line)</Label><Textarea value={disallowPaths} onChange={e => setDisallowPaths(e.target.value)} className="min-h-[100px] font-mono text-sm" /></div>
            <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={allowAll} onChange={e => setAllowAll(e.target.checked)} /> Allow all pages (recommended)</label>
            <Button onClick={generate} className="w-full">Generate Robots.txt</Button>
            {result && (
              <div className="space-y-2">
                <div className="flex justify-between items-center"><p className="text-sm font-medium">Generated robots.txt:</p><Button size="sm" variant="ghost" onClick={copy}><Copy className="h-4 w-4 mr-1" />Copy</Button></div>
                <pre className="bg-muted/50 p-4 rounded-lg text-sm font-mono overflow-x-auto whitespace-pre-wrap">{result}</pre>
              </div>
            )}
          </Card>
          <ToolContentSection {...contentData} />
        </div>
      </div>
    </Layout>
  );
}
