import { Layout } from '@/components/layout/Layout';
import { Helmet } from 'react-helmet-async';

export default function Disclaimer() {
  return (
    <Layout>
      <Helmet>
        <title>Disclaimer - SmartToolsHub</title>
        <meta name="description" content="SmartToolsHub Disclaimer - Important information about the use of our free online tools and services." />
        <link rel="canonical" href="https://smarttoolshub.com/disclaimer" />
      </Helmet>
      <div className="container py-12 md:py-20">
        <div className="max-w-3xl mx-auto prose prose-sm dark:prose-invert">
          <h1 className="font-display text-4xl font-bold mb-8">Disclaimer</h1>
          <p className="text-muted-foreground">Last updated: March 11, 2026</p>

          <h2>General Information</h2>
          <p>The information provided by SmartToolsHub ("we," "us," or "our") on smarttoolshub.com (the "Site") is for general informational purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.</p>

          <h2>Tool Results Disclaimer</h2>
          <p>The results generated by our online tools are provided for informational and educational purposes only. While we strive for accuracy, the results should not be considered as professional advice. Specifically:</p>
          <ul>
            <li><strong>Calculator Tools</strong> (EMI, GST, BMI, Age, Percentage): Results are approximate calculations. For financial decisions, consult a certified financial advisor. For health-related decisions, consult a qualified healthcare professional.</li>
            <li><strong>AI-Powered Tools</strong> (Content Writer, Paraphraser, Grammar Checker, Plagiarism Checker, Translator): AI-generated content should be reviewed and verified before use. We do not guarantee 100% accuracy of AI outputs.</li>
            <li><strong>SEO Tools</strong> (Meta Tag Generator, Keyword Density, Robots.txt Generator, Sitemap Generator): These tools provide recommendations based on general SEO best practices. Results may vary based on specific website requirements.</li>
            <li><strong>Image Tools</strong> (Compressor, Resizer, Converter): Image processing is done in your browser. Quality of output depends on input image quality.</li>
          </ul>

          <h2>No Professional Advice</h2>
          <p>The Site cannot and does not contain professional advice. The tools and information are provided for general informational and educational purposes only and are not a substitute for professional advice.</p>

          <h2>External Links</h2>
          <p>The Site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.</p>

          <h2>Fair Use</h2>
          <p>All tools on SmartToolsHub are provided free of charge for personal and educational use. Commercial use of the tools is permitted, but we are not liable for any outcomes resulting from such use.</p>

          <h2>Data Privacy</h2>
          <p>Most of our tools process data directly in your browser. For AI-powered tools, data is processed through secure servers. We do not store your personal data or content. Please refer to our Privacy Policy for more details.</p>

          <h2>Limitation of Liability</h2>
          <p>In no event shall SmartToolsHub be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Site or its tools.</p>

          <h2>Contact Us</h2>
          <p>If you have any questions about this Disclaimer, please contact us at support@smarttoolshub.com.</p>
        </div>
      </div>
    </Layout>
  );
}
